# Generated by Django 4.2.4 on 2023-08-12 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CacheEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("data", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="DashboardConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keywords", models.TextField()),
                ("refresh_interval", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SocialMediaPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField()),
                ("author", models.CharField(max_length=100)),
                ("platform", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ProcessedPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentiment_score", models.FloatField()),
                ("sentiment_label", models.CharField(max_length=20)),
                ("processed_timestamp", models.DateTimeField()),
                (
                    "original_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sentiment_dashboard.socialmediapost",
                    ),
                ),
            ],
        ),
    ]
